<a href="https://colab.research.google.com/github/OnkarMalawade/MCA-SEM-II-AIML/blob/main/Practical_On_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello")


Hello


In [2]:
student = "Ramesh"
student

'Ramesh'

In [3]:
a1 = 10
type(a1)
type(student)

str

In [4]:
a1 = 20
type(a1)

int

In [6]:
a1 = 10
a2 = 20
a3 = a1*a2
a3

200

In [7]:
a1 != a2

True

In [8]:
True = 1

SyntaxError: cannot assign to True (<ipython-input-8-1598b51f0f76>, line 1)

In [9]:
str1 = "Onkar is Business Guy"
str1

'Onkar is Business Guy'

In [11]:
str2 = '''
Onkar
is
King
'''
str2

'\nOnkar \nis\nKing\n'

In [12]:
str2[0:6]

'\nOnkar'

In [13]:
str2[:3]

'\nOn'

In [14]:
str3 = "Onkar"
len(str3)

5

In [15]:
str3.upper()

'ONKAR'

In [16]:
str3.lower()

'onkar'

In [18]:
str2.lower()


'\nonkar \nis\nking\n'

In [17]:
str3.replace('O', 'D')

'Dnkar'

In [20]:
str4 = "MCA MCA MCA IS BAD"
str4.count("MCA")

3

In [21]:
tup1 = (1,"b",True,2)
tup1

(1, 'b', True, 2)

In [22]:
tup1[0:3]

(1, 'b', True)

In [23]:
len(tup1)

4

In [24]:
tup2 = (3,"c",False,4)
tup2
tup1+tup2

(1, 'b', True, 2, 3, 'c', False, 4)

In [25]:
tup1*2

(1, 'b', True, 2, 1, 'b', True, 2)

tup1*3+tup2

In [27]:
list1 = [1,"b",True,2]
list1

[1, 'b', True, 2]

In [30]:
list1.append("SJ")
list1

[1, 'b', True, 2, 'SJ', 'SJ']

In [31]:
list1.reverse()

In [32]:
list1.pop()

1

In [33]:
list1.reverse()
list1

['b', True, 2, 'SJ', 'SJ']

In [34]:
list1.reverse()
list1

['SJ', 'SJ', 2, True, 'b']

In [35]:
list1.insert(2,"OM")
list1

['SJ', 'SJ', 'OM', 2, True, 'b']

In [36]:
list2 = [1,3,2,5,7,3,2,1]
list2.sort()
list2

[1, 1, 2, 2, 3, 3, 5, 7]

In [37]:
def hello():
  print("This is Hello Function")

hello()

This is Hello Function


In [39]:
def CheckOddEven(x):
  if x%2 == 0:
      print("This is Even Number")
  else:
      print("This is Odd Number")

CheckOddEven(11)

This is Odd Number


In [40]:
g = lambda x:x*x*x

g(4)

64

In [42]:
list4 = [1,2,3,4,5,6,7,98,8,87,9]
filterlist = list(filter(lambda x : x%2==0, list4))
filterlist

[2, 4, 6, 98, 8]

In [43]:
from functools import reduce
r = reduce(lambda x,y: x+y,list4)
r

230

In [44]:
#numpy array
import numpy as np
n1 = np.array([1,2,3])
n1

array([1, 2, 3])

In [45]:
n2 = np.array([[1,2,3],[4,7,8],[9,8,3]])
n2

array([[1, 2, 3],
       [4, 7, 8],
       [9, 8, 3]])

In [47]:
n3 = np.zeros((1,2))
n3


array([[0., 0.]])

In [48]:
n4 = np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
n5 = np.zeros((2,5))
n5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
n6 = np.full((4,4),4)
n6

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [52]:
n7 = np.arange(1,21)
n7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
n8 = np.arange(20,90,4)
n8

array([20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84,
       88])

In [55]:
n9 = np.array([[1,2,3,4],[6,7,8,9]])
n9.shape

(2, 4)

In [56]:
n9.shape = (4,2)
n9

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [57]:
n9.shape = (8,1)
n9

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7],
       [8],
       [9]])

In [58]:
n9.shape = (1,8)
n9

array([[1, 2, 3, 4, 6, 7, 8, 9]])

In [60]:
n11 = np.array([1,2,3])
n12 = np.array([4,7,8])

np.vstack((n11,n12))

array([[1, 2, 3],
       [4, 7, 8]])

In [61]:
np.hstack((n11,n12))

array([1, 2, 3, 4, 7, 8])

In [62]:
np.column_stack((n11,n12))


array([[1, 4],
       [2, 7],
       [3, 8]])

In [63]:
m1 = np.array([10,20,30,40,50])
m2 = np.array([40,70,100,20])

np.intersect1d(m1,m2)


array([20, 40])

In [64]:

np.setdiff1d(m1,m2)


array([10, 30, 50])

In [67]:
k1 = np.array([1,2,3])
k2 = np.array([4,5,6])

np.sum([k1,k2])


21

In [68]:
np.sum([k1,k2],axis = 0)

array([5, 7, 9])

In [69]:
np.sum([k1,k2],axis = 1)

array([ 6, 15])

In [70]:
k3 = np.array([1,2,3,4])
np.save('myArray',k3)
k4 = np.load('myArray.npy')
k4

array([1, 2, 3, 4])

In [71]:
#Panda
import pandas as pd
s1 = pd.Series([1,2,3,4])
s1

0    1
1    2
2    3
3    4
dtype: int64

In [72]:
s2=pd.Series([1,2,3,4],index=['a','b','c','d'])
s2

a    1
b    2
c    3
d    4
dtype: int64

In [73]:
s3 = pd.Series({'amey':10,'akshay':20,'adit':30})
s3

amey      10
akshay    20
adit      30
dtype: int64

In [74]:
s3 = pd.Series({'amey':10,'akshay':20,'adit':30})
s3[0:1]

amey    10
dtype: int64

In [75]:
# pandas dataframe
s4 = pd.DataFrame({"Names":['Nazrana','Onkar','Esha'],"Marks":[100,0,100],"Mobile":[9000,9888,9020]})
s4

Names  Marks  Mobile
0  Nazrana    100    9000
1    Onkar      0    9888
2     Esha    100    9020

from matplotlib import pyplot as plt
s4['Marks'].plot(kind='hist', bins=20, title='Marks')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
s4['Mobile'].plot(kind='hist', bins=20, title='Mobile')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
s4.groupby('Names').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
s4.plot(kind='scatter', x='Marks', y='Mobile', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
s4['Marks'].plot(kind='line', figsize=(8, 4), title='Marks')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
s4['Mobile'].plot(kind='line', figsize=(8, 4), title='Mobile')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(s4['Names'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(s4, x='Marks', y='Names', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(s4['Names'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(s4, x='Mobile', y='Names', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)